set(CASTOR_OBS_VERSION "32.1.2")
set(CASTOR_OBS_SDK_REVISION "1")

set(
    CASTOR_OBS_SDK_VERSION
    "${CASTOR_OBS_VERSION}-castor.${CASTOR_OBS_SDK_REVISION}"
)

set(CASTOR_OBS_SDK_PLATFORM "win-x64")

set(
    CASTOR_OBS_SDK_ARCHIVE_NAME
    "Castor.Obs.Sdk.${CASTOR_OBS_SDK_PLATFORM}-${CASTOR_OBS_SDK_VERSION}.zip"
)
