name: Engine CI

on:
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Configure engine
        run: cmake --preset windows-x64

      - name: Build engine
        run: cmake --build --preset windows-x64-release

      - name: Install engine
        run: >
          cmake --install build/windows-x64
          --config Release
          --prefix artifacts/runtime/win-x64

      - name: Restore .NET
        run: dotnet restore Castor-Engine.sln

      - name: Build .NET
        run: >
          dotnet build Castor-Engine.sln
          --configuration Release
          --no-restore

      - name: Test .NET
        run: >
          dotnet test Castor-Engine.sln
          --configuration Release
          --no-build
